[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "none"
opacity = 0.92
blur = true

[font]
size = 11.5
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = "Block"

# falcon colorscheme for alacritty
# by fenetikm, https://github.com/fenetikm/falcon
[colors]

# Default colors
[colors.primary]
  background = "#0F0F0F"
  foreground = "#FF4C4C"

# Cursor colors
[colors.cursor]
  text    = '0x020221'
  cursor  = '0xffe8c0'

# Normal colors
[colors.normal]
  black   = "#1C1C1C"
  red     = "#FF4C4C"
  green   = "#5AF78E"
  yellow  = "#F3F99D"
  blue    = "#57C7FF"
  magenta = "#FF6AC1"
  cyan    = "#9AEDFE"
  white   = "#F1F1F0"

# Bright colors
[colors.bright]
  black   = "#686868"
  red     = "#FF6B6B"
  green   = "#69FF94"
  yellow  = "#FFFFA5"
  blue    = "#7CDFFF"
  magenta = "#FF92D0"
  cyan    = "#A4FFFF"
  white   = "#FFFFFF"

[selection]
save_to_clipboard = true

[debug]
log_level = "Warn"

live_config_reload = true
